name: todo
title: Todo
version: '0.5.0'
summary: A command line task management utility
description: |
  A command line application to manage tasks and
  TODOs. Tasks can be given one of 4 priority
  levels, and can either be a \"global\" task that
  is accessible from anywhere, or a \"local\" task
  that is specific to a directory and its childen.

base: core20
grade: devel
confinement: devmode

apps:
  todo:
    command: usr/local/bin/todo

build-packages:
  - build-essential
  - automake
  - ccache
  - g++

parts:
  todo:
    source: .
    source-type: git
    plugin: cmake
    build-packages: [g++]
